[tool.poetry]
name = "plannerbenchmark"
version = "0.1.1"
description = "Benchmark suite for local planner in dynamic environment."
authors = ["Max Spahn <m.spahn@tudelft.nl>"]

[tool.poetry.dependencies]
python = "^3.6.2,<3.11"
forwardkinematics = {git = "https://git@github.com/maxspahn/forwardKinematics.git", rev = "main"}
planarenvs = {git = "https://git@github.com/maxspahn/gym_envs_planar.git", rev = "master"}
urdfenvs = {git = "https://git@github.com/maxspahn/gym_envs_urdf.git", rev = "master"}
robotmpcs = {git = "https://git@github.com/maxspahn/robot_mpcs.git", rev = "main", optional = true}
motion-planning-scenes= {git = "https://git@github.com/maxspahn/motion_planning_scenes.git", rev = "main"}
# fabrics = {path = "../../../../code/fabrics", optional = true}
Sphinx = { version = "4.2.0", optional = true }
sphinx-rtd-theme = { version = "1.0.0", optional = true }
sphinxcontrib-napoleon = { version = "0.7", optional = true }


[tool.poetry.extras]
fabric = ['fabrics']
mpc = ['robotmpcs']
docs = ["Sphinx", "sphinx-rtd-theme", "sphinxcontrib-napoleon"]

[tool.poetry.dev-dependencies]
black = "^22.3.0"
pytest = "^6.2"
pylint = "^2.13.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
